### ISSUE TITLE
Rotate yaw in position control mode,the horizontal velocity is wrong with gps measured velocity.

### ISSUE THREAD

**Issue by garlinplus** [PX4/PX4-ECL#980]

**Comment by garlinplus** [comment]
the log address is https://logs.px4.io/plot_app?log=912ad7f9-74e4-45c1-9a74-5a6072930797

**Comment by CarlOlsson** [comment]
That's a very interesting logfile, the IMU biases diverge during the rotation. Do you think you could collect a replay logfile during the same maneuver?

**Comment by garlinplus** [comment]
> he IMU biases diverge during the rotation

![image](https://user-images.githubusercontent.com/12841057/108344023-98e6aa00-7217-11eb-9c0f-8a244bce6a43.png)
![image](https://user-images.githubusercontent.com/12841057/108344065-a439d580-7217-11eb-8773-30da3d4ed757.png)
The gyro and acc bias seems to be large than formal flying log as followed:
![image](https://user-images.githubusercontent.com/12841057/108344208-d2b7b080-7217-11eb-9427-737dc7779d92.png)
![image](https://user-images.githubusercontent.com/12841057/108344264-e3682680-7217-11eb-8975-ddd556ae9190.png)

**Comment by garlinplus** [comment]
> That's a very interesting logfile, the IMU biases diverge during the rotation. Do you think you could collect a replay logfile during the same maneuver?

The imu bias is larger than formal flying,but Even if as that,the gps and mag measure can not correct those with ekf measure update process?

**Comment by abishekvupputur** [comment]
I notice that your yaw angular rate is about 100 deg/s. I think it is quite possible that you are measuring centrifugal acceleration in the body reference frame. Due to lack of observability of centrifugal force, in body frame it is interpreted like a "added bias (function of spin) during large yaw rates". So it makes sense that the bias estimates is diverging to accommodate for this error caused as a consequence of spin. I think the EKF is working perfectly to accommodate this. There 2 possible ways to get rid of this problem.
1. Centre your IMU closer to the center of gravity of the drone. The closer you are, lower is your "acceleration bias divergence".
2. Write a small calibration routine, manually calculate the offset of imu from the centre of gravity and calculate your acceleration caused as a result of spin before passing the values through your EKF. This compensation for the added acceleration can be done by subtracting a_c from the measured acceleration from IMU:
>> a_c = ω x ω x r.
where,
a_c - calculated acceleration in [x,y,z]
ω - body angular velocity in [x,y,z] (gyro bias corrected values)
r - imu offset from cog in [x,y,z]

May be in future, we can also have a IMU offset parameter to account for this error. Or extend the EKF to include IMU offset prediction based on body angular rate to measured acceleration.

**Comment by abishekvupputur** [comment]
[](url)https://github.com/PX4/PX4-ECL/issues/621

**Comment by priseborough** [comment]
This looks like the issue that was fixed by https://github.com/PX4/PX4-ECL/pull/1026

Please re-open if not fixed for you.
